require 'rubygems'
require 'zip/zipfilesystem'
require 'fileutils'
require 'odf-report/file_ops'
require 'odf-report/hash_gsub'
require 'odf-report/section'
require 'odf-report/table'
require 'odf-report/report'
